version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=bookstore
      - POSTGRES_PASSWORD=bookstore
    ports:
      - '54321:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local